version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway-image
    container_name: gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - STUFF_SHARING_APP_SERVER_URL=http://server:9090
#      - TZ=Europe/Moscow

  server:
    build: server
    image: server-image
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stuff_sharing_app
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
#      - TZ=Europe/Moscow

  db:
    image: postgres:14.7-alpine
    container_name: db-container
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=stuff_sharing_app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      - TZ=Europe/Moscow